apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: up2c7mx5x-nodejs
  janus-idp.io/tekton: up2c7mx5x-nodejs
  backstage.io/kubernetes-id: up2c7mx5x-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: up2c7mx5x-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
